baseURL = 'https://www.rizqyromadhona.my.id'
languageCode = 'en-us'
title = 'Blog ID'
theme = 'blog'
enableRobotsTXT = 'true'
paginate = 6
summaryLength = 40
copyright = '2022. Blog ID - All rights reserved'

[Author]
    name = 'Rizqy Romadhon A'
    email = 'rizqyblogspot@gmail.com'
[params]
  Description = 'Blog ID is a blog that covers many topics, such as Health, Technology, Fitness, Finance, Psychology, Tutorials, and many others.'
  favicon = 'https://img.icons8.com/external-tanah-basah-basic-outline-tanah-basah/512/202124/external-health-sport-tanah-basah-basic-outline-tanah-basah.png'
  twitter = 'Rizqy'
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
[markup.goldmark.renderer]
  unsafe = true
[taxonomies]
  tags = 'tags'
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = 'keywords'
    weight = 90
  [[related.indices]]
    name = "title"
    weight = 100